baseURL = 'https://dhyeok.github.io/'
languageCode = 'ko-kr'
title = 'Hyeok Dev Blog'
theme = 'PaperMod'
disableKinds = ['RSS']

[author]
  name = 'hyeok'

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = 'auto'

[menu]
  [[menu.main]]
    identifier = 'ai'
    name = 'AI'
    url = '/all/ai/'
    weight = 10
  [[menu.main]]
    identifier = 'infra'
    name = 'Infra'
    url = '/all/infra/'
    weight = 20
  [[menu.main]]
    identifier = 'tech'
    name = 'Tech'
    url = '/all/tech/'
    weight = 30
  [[menu.main]]
    identifier = 'culture'
    name = 'Culture'
    url = '/all/culture/'
    weight = 40
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 50
  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/'
    weight = 60

[taxonomies]
  category = 'categories'
  tag = 'tags'
