baseURL = 'https://dhyeok.github.io/'
languageCode = 'ko-kr'
title = 'Hyeok Dev Blog'
theme = 'PaperMod'
disableKinds = ['RSS']

[author]
  name = 'hyeok'

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = 'auto'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10

  [[menu.main]]
    identifier = 'posts-ai'
    parent = 'posts'
    name = 'AI'
    url = '/categories/ai/'
    weight = 1
  [[menu.main]]
    identifier = 'posts-infra'
    parent = 'posts'
    name = 'Infra'
    url = '/categories/infra/'
    weight = 2
  [[menu.main]]
    identifier = 'posts-tech'
    parent = 'posts'
    name = 'Tech'
    url = '/categories/tech/'
    weight = 3
  [[menu.main]]
    identifier = 'posts-culture'
    parent = 'posts'
    name = 'Culture'
    url = '/categories/culture/'
    weight = 4

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = 30
  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/'
    weight = 40

[taxonomies]
  category = 'categories'
  tag = 'tags'
